# For conda build
package:
  name: dde
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }} # set by build.sh, which gets from rmgpy/__init__.py

source:
  path: .

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python

  run:
    - python
    - nose
    - keras=1.2.2
    - tqdm
    - pymongo
    - theano=0.9.0
    - pydot-ng
    - rmg # we need to remove it if we build it for rmg to use

test:
  source_files:
    - '*'
  requires:
    - nose
  imports:
    - dde
  commands:
    - export KERAS_BACKEND=theano
    - make -C $SRC_DIR test-cnn [unix]

about:
  home: http://github.com/KEHANG/DataDrivenEstimator
  license: MIT
  summary: "A package of major data driven estimators for thermochemistry and kinetics."
